<a href="https://colab.research.google.com/github/HWKim-postech/Do-you-really-know-about-this-function-/blob/main/Tensor%20and%20Parser.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Functions

Last time, we studied basic FC, CNN codes. If you are a very beginning about ML, I think there're tons of functions that you've never seen before.

When I studied ML, I was also confused with there functions and people didn't let me know easily.

So, in this section, we're gonna look carefully about the functions in ML.

I want to start with : Tensor(axis), Parser.

##Actually, tensor is usually not considered as a typical "function". But Tensor is the most important concept you have to understand. 

When we make our ML model, we have to use hundreds of features as input. This is not a 1d, 2d array. So smart people invented tensor which is beautiful tool to deal with matrix that have large dimension.

Let's start with basic matrices.

This is the 1X3 matrix (or array)

In [23]:
import numpy as np
import torch
Mat1d = np.array([1, 2, 3])
print(Mat1d)

print("Rank:%d Size:%d"%(Mat1d.ndim, Mat1d.size))

[1 2 3]
Rank:1 Size:3


And 3X3 matrix (2d)

In [22]:
Mat2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Mat2d)

print("Rank:%d Size:%d"%(Mat2d.ndim, Mat2d.size))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank:2 Size:9


And actually we can make 3D matrix by numpy. But I'll make it by using tensor(torch)

In [53]:
Tensor3d = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]],[[13, 14,15], [16, 17, 18]]])

print(Tensor3d)

print("Rank: %d"%Tensor3d.ndim, Tensor3d.size(), Tensor3d.type())

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])
Rank: 3 torch.Size([3, 2, 3]) torch.LongTensor


So, you can extend it to 4, 5, 6-----as many dimensions as you want.

I think you already know about matrix multiplication, add, element-wise, inplace operate--- this properties are quite easy and intuitive.

But, including me, "axis" is very confusing. 

I want to throw a question : What's gonna happen if we add Tensor3d along dim = 0, 1, 2?

In [40]:
#First , dim = 0
print(Tensor3d.sum(dim = 0))
print("\n")
#Second, dim = 1
print(Tensor3d.sum(dim = 1))
print("\n")
#dim = 2
print(Tensor3d.sum(dim = 2))

tensor([[21, 24, 27],
        [30, 33, 36]])


tensor([[ 5,  7,  9],
        [17, 19, 21],
        [29, 31, 33]])


tensor([[ 6, 15],
        [24, 33],
        [42, 51]])


What happens? Just imagine 3d matrix and think about what happened.



I'm sure that you could easily find out the principal. 

1. dim = 0 : Sum is operated by channel by channel. Same column, row coordinate elements are summed.

2. dim = 1 : In each channel, sum is operated by collapsing column. So it changes to 3 of 1X3 matrices, and turn into 3X3 matrix.

3. dim = 2 : In each channel, sum is operated by collapsing row. So it changes to 3 of 1X2 matrices, and turn into 3X2 matrix.

You can find the web site in my basic FC, CNN codes that visualize the axis and dimension. ("collapse row, column" is an expression of this web site.)

Next, parser. parser eases meaningless work. We can just add constants and use it.

In [72]:
import argparse
parser = argparse.ArgumentParser()

parser.add_argument("--BatchSize", type = int, default = 32, help = "Batch size")
parser.add_argument("--Epochs", type = int, default = 100, help = "Epochs")
parser.add_argument("--lr", type = float, default = 0.003, help = "Learning Rate")
parser.add_argument("--betas", type = float, default = (0.9, 0.999), help = "beta1, beta2 for Adam")

opt = parser.parse_args(args=[])


print(opt.betas, opt.lr)

(0.9, 0.999) 0.003


It's done! Now we can easily use and adjust parameters & hyper parameters.